import express from 'express';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';
import {
    getNotes,
    completeNote,
    deleteNote,
    createSession,
    getSession,
    verifyAuthCode
} from './db-service.js';
import { getClientConfig } from './i18n.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const app = express();

// Maximum accepted age of a Telegram Mini App initData, in seconds.
// Older data is rejected even if the signature is valid, to limit replay
// of intercepted data.
const TMA_MAX_AGE_SECONDS = 24 * 60 * 60; // 24 hours
// Small tolerance for clock skew between client and server.
const TMA_CLOCK_SKEW_TOLERANCE_SECONDS = 5 * 60; // 5 minutes

function verifyTmaData(initData) {
    if (!initData) return false;
    const params = new URLSearchParams(initData);
    const hash = params.get('hash');
    params.delete('hash');

    const authDate = params.get('auth_date');
    if (!authDate) return false;

    const ageSeconds = Math.floor(Date.now() / 1000) - parseInt(authDate, 10);
    if (
        Number.isNaN(ageSeconds) ||
        ageSeconds > TMA_MAX_AGE_SECONDS ||
        ageSeconds < -TMA_CLOCK_SKEW_TOLERANCE_SECONDS
    ) {
        return false;
    }

    const dataCheckString = Array.from(params.entries())
        .map(([key, value]) => `${key}=${value}`).sort().join('\n');
    const secretKey = crypto.createHmac('sha256', 'WebAppData')
        .update(process.env.TELEGRAM_BOT_TOKEN).digest();
    const calculatedHash = crypto.createHmac('sha256', secretKey)
        .update(dataCheckString).digest('hex');
    return calculatedHash === hash;
}

// Middleware that checks the dashboard session token
async function checkAuth(req, res, next) {
    const token = req.headers['authorization'];
    const chatId = req.query.chatId || req.body?.chatId;

    const session = await getSession(token);
    if (!session || session.chatId !== String(chatId)) {
        return res.status(403).json({ error: "Invalid or expired session" });
    }
    req.chatId = session.chatId;
    next();
}

export function startWebServer() {
    app.use(express.json());
    app.use(express.static(path.join(__dirname, 'public')));

    // Language, locale, timezone and UI strings for the dashboard
    app.get('/api/locale', (req, res) => {
        res.json(getClientConfig());
    });

    // Automatic authentication (Telegram Mini App)
    app.post('/api/auth/telegram', async (req, res) => {
        const { initData } = req.body;
        if (!verifyTmaData(initData)) return res.status(401).send();

        const user = JSON.parse(new URLSearchParams(initData).get('user'));
        const token = await createSession(String(user.id));
        res.json({ token, chatId: String(user.id) });
    });

    // Manual authentication with the 6-digit code generated by /login
    app.post('/api/auth/code', async (req, res) => {
        const { chatId, code } = req.body || {};
        if (!chatId || !code) {
            return res.status(400).json({ error: "chatId and code are required" });
        }

        const valid = await verifyAuthCode(chatId, code);
        if (!valid) {
            return res.status(401).json({ error: "Invalid or expired code" });
        }

        const token = await createSession(String(chatId));
        res.json({ token, chatId: String(chatId) });
    });

    // Tasks API (notes)
    app.get('/api/tasks', checkAuth, async (req, res) => {
        const tasks = await getNotes(req.chatId, ['active', 'notified']);
        res.json(tasks);
    });

    // Mark a task as completed / renew it if recurring
    app.post('/api/tasks/:id/complete', checkAuth, async (req, res) => {
        const taskId = parseInt(req.params.id);
        try {
            const success = await completeNote(taskId, req.chatId);
            if (success) {
                res.json({ success: true, message: "Task updated successfully" });
            } else {
                res.status(404).json({ error: "Task not found or not modified" });
            }
        } catch (e) {
            res.status(500).json({ error: e.message });
        }
    });

    // Permanently delete a task
    app.delete('/api/tasks/:id', checkAuth, async (req, res) => {
        const taskId = parseInt(req.params.id);
        try {
            const success = await deleteNote(taskId, req.chatId);
            if (success) {
                res.json({ success: true, message: "Task deleted successfully" });
            } else {
                res.status(404).json({ error: "Task not found" });
            }
        } catch (e) {
            res.status(500).json({ error: e.message });
        }
    });

    const PORT = process.env.WEB_PORT || 3000;
    app.listen(PORT, () => console.log(`🌐 Dashboard listening on port ${PORT}`));
}
